import { COLORS } from "./theme";
import { StyleSheet } from "react-native";
import { GlobalStyles } from "./GlobalStyles";

export const styles = StyleSheet.create({
    ...GlobalStyles,
    listContent: {
        ...GlobalStyles.scrollContent,
        paddingHorizontal: 20,
        paddingBottom: 100,
    },
    headerContainer: {
        paddingTop: 12,
        paddingBottom: 24,
    },
    topBar: {
        ...GlobalStyles.rowBetween,
        marginBottom: 20,
        minHeight: 48,
    },
    backBtn: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 24,
        backgroundColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    backBtnText: {
        color: '#1f2937',
        fontSize: 14,
        fontWeight: '600',
    },
    headerRight: {
        flexDirection: 'row',
        marginLeft: 'auto',
        gap: 12,
    },
    actionBtn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.iconBg,
    },
    title: {
        fontSize: 32,
        fontWeight: '800',
        color: COLORS.title,
        marginBottom: 8,
        letterSpacing: -0.5,
    },
    searchContainer: {
        ...GlobalStyles.card,
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        paddingHorizontal: 16,
        height: 48,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.border,
        shadowColor: COLORS.title,
        shadowOpacity: 0.04,
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: COLORS.title,
        paddingVertical: 0,
    },
    clearButton: {
        padding: 4,
    },
    subtitle: {
        ...GlobalStyles.subtitle,
        lineHeight: 24,
        marginBottom: 12,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 60,
    },
    emptyIconBox: {
        ...GlobalStyles.iconContainer,
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 20,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: COLORS.text,
        marginBottom: 8,
    },
    emptySubText: {
        ...GlobalStyles.subtitle,
        textAlign: 'center',
        paddingHorizontal: 32,
        lineHeight: 22,
    },
    fab: {
        position: 'absolute',
        bottom: 85,
        right: 24,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    }
});